repos:
  - repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.1.4
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.17.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/(toml-test|toml-spec-tests)/.*
      - id: end-of-file-fixer
        exclude: ^tests/(toml-test|toml-spec-tests)/.*
      - id: debug-statements

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
